name: Enrich Leads

on:
  workflow_dispatch:
    inputs:
      task:
        description: 'What to run'
        required: true
        type: choice
        options:
          - 'Test (5 companies)'
          - 'Enrich Companies'
          - 'Enrich Leads'
          - 'Enrich Both (Companies + Leads)'
          - 'Validate Setup Only'
      limit:
        description: 'Limit number of records (leave empty for all)'
        required: false
        type: string

jobs:
  enrich:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Create config from secrets
      env:
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        python setup.py
    
    - name: Run selected task
      env:
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        case "${{ github.event.inputs.task }}" in
          "Test (5 companies)")
            echo "Running test with 5 companies..."
            python enrich_companies.py --limit 5
            ;;
          "Enrich Companies")
            if [ -n "${{ github.event.inputs.limit }}" ]; then
              echo "Enriching companies (limit: ${{ github.event.inputs.limit }})..."
              python enrich_companies.py --limit ${{ github.event.inputs.limit }}
            else
              echo "Enriching all companies..."
              python enrich_companies.py
            fi
            ;;
          "Enrich Leads")
            if [ -n "${{ github.event.inputs.limit }}" ]; then
              echo "Enriching leads (limit: ${{ github.event.inputs.limit }})..."
              python enrich_leads.py --limit ${{ github.event.inputs.limit }}
            else
              echo "Enriching all leads..."
              python enrich_leads.py
            fi
            ;;
          "Enrich Both (Companies + Leads)")
            if [ -n "${{ github.event.inputs.limit }}" ]; then
              echo "Enriching companies and leads (limit: ${{ github.event.inputs.limit }} each)..."
              python enrich_companies.py --limit ${{ github.event.inputs.limit }}
              python enrich_leads.py --limit ${{ github.event.inputs.limit }}
            else
              echo "Enriching all companies and leads..."
              python enrich_companies.py
              python enrich_leads.py
            fi
            ;;
          "Validate Setup Only")
            echo "Validating setup..."
            python validate_setup.py
            ;;
        esac
    
    - name: Upload enrichment log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: enrichment-log
        path: enrichment.log
        retention-days: 30
